export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_CATEGORY = 'GET_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const INSERT_CATEGORY = 'INSERT_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
