// CATEGORIES
export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_CATEGORY = 'GET_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const INSERT_CATEGORY = 'INSERT_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

// CATEGORY TYPES
export const GET_CATEGORY_TYPE = 'GET_CATEGORY_TYPE'

// MONTHLY LOGS
export const GET_USER_MONTHLY_LOG_BY_MONTH = 'GET_USER_MONTHLY_LOG_BY_MONTH'
export const INSERT_MONTHLY_LOG = 'INSERT_MONTHLY_LOG'
